### ISSUE TITLE
Running some commands in console produces errors

### ISSUE THREAD

**Issue by Samvbnm** [mc-server/Core#124] opened 2015-03-16 19:46 UTC
running commands like tps and weather in the server console produces errors that it didn't in previous versions. Console output below \/
tps:
```
[15:57:55] Executing console command: "tps"
[15:57:55] LUA: Plugins/Core/tps.lua:6: attempt to call method 'SendMessageInfo' (a nil value)
[15:57:55] Stack trace:
[15:57:55] Plugins/Core/tps.lua(6): (no name)
[15:57:55] Stack trace end
[15:57:55] Error in plugin Core calling function ()
[15:57:55] Unknown command, type 'help' for all commands.
```
weather:
```
[15:58:24] Executing console command: "weather"
[15:58:24] LUA: Plugins/Core/functions.lua:175: attempt to call method 'GetWorld' (a nil value)
[15:58:24] Stack trace:
[15:58:24] Plugins/Core/functions.lua(175): GetWorld
[15:58:24] Plugins/Core/weather.lua(50): (no name)
[15:58:24] Stack trace end
[15:58:24] Error in plugin Core calling function ()
[15:58:24] Unknown command, type 'help' for all commands
```

**Comment by Samvbnm** [comment] 2015-03-16 19:48
I think this is in the right place now

**Comment by NiLSPACE** [comment] 2015-03-16 19:56
Yes thank you :)

You were using /tps on console? That's pretty weird, because the command handler is made for a player command, so it's no wonder that it failed.

Something is going on at https://github.com/mc-server/Core/blob/master/functions.lua#L175
I think it should be fixed if we change that line to 
```lua
return (Player ~= nil and Player:GetName()) or cRoot:Get():GetDefaultWorld()
```

**Comment by Samvbnm** [comment] 2015-03-16 19:58
nope I was tpying "tps" (no quotes) into the console

**Comment by SphinxC0re** [comment] 2015-03-16 19:59
we should implement another standard right: console. It would allow the console to execute things. Some commands shouldn't be executed by the console and people should be able to regulate that

**Comment by tigerw** [comment] 2015-03-16 20:02
People are able to control console and player commands independently, however, it was overlooked in Core's commands registration file, so both console and player executed tps counter commands go to the same handler, designed for in-game use, which is causing the error.

**Comment by Samvbnm** [comment] 2015-03-16 20:22
NiLSPACE I tried your fix and it didn't help :(

**Comment by NiLSPACE** [comment] 2015-03-16 20:49
Could you then try 
```lua
return (tolua.type(Player) == 'cPlayer' and Player:GetName()) or cRoot:Get():GetDefaultWorld()
```

**Comment by Samvbnm** [comment] 2015-03-16 20:50
I will soon

**Comment by Samvbnm** [comment] 2015-03-16 21:05
Still didn't help
heres the out put with your fix;
tps
[18:03:41] Executing console command: "tps"
[18:03:41] LUA: Plugins/Core/tps.lua:6: attempt to call method 'SendMessageInfo' (a nil value)
[18:03:41] Stack trace:
[18:03:41]   Plugins/Core/tps.lua(6): (no name)
[18:03:41] Stack trace end
[18:03:41] Error in plugin Core calling function <callback>()
[18:03:41] Unknown command, type 'help' for all commands.
weather
[18:03:47] Executing console command: "weather"
[18:03:47] LUA: Plugins/Core/functions.lua~:175: attempt to call method 'GetName' (a nil value)
[18:03:47] Stack trace:
[18:03:47]   Plugins/Core/functions.lua~(175): GetWorld
[18:03:47]   Plugins/Core/weather.lua(50): (no name)
[18:03:47] Stack trace end
[18:03:47] Error in plugin Core calling function <callback>()
[18:03:47] Unknown command, type 'help' for all commands.

**Comment by Samvbnm** [comment] 2015-03-16 21:19
your fix also breaks in-game use of /weather

**Comment by NiLSPACE** [comment] 2015-03-16 21:33
I don't think the console is even supposed to be able to use those commands though. It even uses the player command handler. This means it doesn't get a cPlayer object with it. Of course we get an error if we try that.

**Comment by Samvbnm** [comment] 2015-03-16 21:34
they used to work though and I think that weather and tps are still useful when invoked from the console

**Comment by NiLSPACE** [comment] 2015-03-16 21:35
The damage was done here: 4183d6c. The `HandleConsoleWeather` function was removed and replaced with `HandleWeatherCommand`.

**Comment by Samvbnm** [comment] 2015-03-16 21:38
I think its definitely worth re-implimenting

**Comment by jonfabe** [comment] 2015-03-16 22:44
So as the one who authored that commit, I'm going to chime in here - the separate command was removed because having two separate places to maintain the same code means one part is inevitably not in sync with the other part. That said, when that commit landed it worked fine, the real question is what changed after that commit?

**Comment by Samvbnm** [comment] 2015-03-16 22:46
Yeah I was gonna say that because the build I was previously using that worked would only have been a month old max

**Comment by jonfabe** [comment] 2015-03-16 23:01
Yes, and it will be an issue in multiple places throughout the code base, since is (was?) how standard lua worked as well - no reference passed to a function argument meant it was just treated as a nil value, which was functionally equivalent to boolean false. Does anyone know if that changed in a recent lua update or is it just an implementation change of the api for mcserver only?

**Comment by jonfabe** [comment] 2015-03-17 01:23
So, digging into this more, it appears MCServer/#1807 is to blame. It looks like they added additional information being passed to the functions? Anyone with knowledge of the matter care to comment?

**Comment by madmaxoft** [comment] 2015-03-17 09:12
Yeah, that change is probably the cause. The old console command handler received just 1 parameter, so the other declared parameters received the value `nil`. Now they receive a string value, that's why the checks fail.

I believe that the MCS change is worth it, so we just need to fix the Core handlers. I think a simple check like
```lua
if (type(Player) == "string") then
  -- Console command
else
  -- In-game command
end
```

**Comment by SphinxC0re** [comment] 2015-03-17 10:54
We could add a method that does that like
```lua
if(Player.isRealPlayer()) then
  -- Console command
else
  -- In-game command
end
```

**Comment by madmaxoft** [comment] 2015-03-17 11:10
1. Can't (Player is a raw string for console commands, can't attach methods to strings)
2. Code smell. It's just so much better to have two separate handlers for separate situations. Of course the internal code could be implemented in a common subroutine that both of these handlers call, but separation here makes total sense.

**Comment by Samvbnm** [comment] 2015-03-17 14:12
Can confirm that xoft's fix worms like a charm!

**Comment by NiLSPACE** [comment] 2015-03-17 14:26
You can add methods to strings: https://github.com/NiLSPACE/MC-Web-Server/blob/master/functions.lua#L15

**Comment by madmaxoft** [comment] 2015-03-17 14:28
You added a method to the `string` table, not to the `string` datatype as such.
Yes, it is possible to add methods to the string datatype, using metatables, but it's just a big WTF - why should each string have a function determining whether it is a player or not?

**Closed** 2015-03-19 16:55 UTC
